pizzas/urls.py
"""Defines URL pattern for pizzas."""

from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all the available pizzas
    path('pizzas/', views.pizzas, name='pizzas'),
    # Show all the toppings for each pizza
    path('pizzas/<int:pizza_id>/', views.topping, name='topping'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/models.py
from django.db import models

class Pizza(models.Model):
    """pizza name"""
    name = models.CharField(max_length=200)
    #date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name


class Topping(models.Model):
    """pizza toppings"""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    #date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    

pizzas/views.py
from urllib import request

from django.shortcuts import render

from .models import Pizza, Topping


def index(request):
    """The home page for pizzas."""
    return render(request, 'pizzas/index.html')
    
def pizzas(request):
    """Show all the available pizzas"""
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)
   
   
def topping(request, pizza_id):
    """Show a single pizza and all its toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('name')
    context = {'pizza':pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a>
    <a href="{% url 'pizzas:pizzas' %}">pizzas</a>
</p>

{% block content %}{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>This is home page of pizzeria (:</p>
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

<p>Pizza: {{pizza}}</p>
<ul>
    {% for topping in toppings %}
    <li>
        <p>{{topping.name}}</p>
        <p>{{topping.text|linebreaks}}</p>
    </li>
    {% empty %}
    <li>Thre are no Toppings for this pizza yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}
    <li>
        <a href="{% url 'pizzas:topping' pizza.id %}">{{pizza}}</a>
    </li>
    {% empty %}
        <li>No tpizza have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}